### PR TITLE
Reduced method calls for init_drivers() and renamed to setupDriver()

### PR DESCRIPTION
**Pull request by rsfxiii**

### CODE REVIEW

**Review by nikshepsvn — CHANGES_REQUESTED** [review]
Some really solid changes Ryan! Just noticed for the RPi initialization part you're returning the firefox_options object instead of the webdriver object. Fix that up and I'll merge the changes!

**Comment by rsfxiii** [comment]
*facepalm*

nvm. I'm terrible with github right now (and usually)

Update: @nikshepsvn Good to go now!

**Review by nikshepsvn — CHANGES_REQUESTED** [review]
Hey Ryan, really good stuff. But for the Firefox webdriver object we're passing a path p to the object for initialization, you've taken that out so it wouldn't be possible for the object to get the right driver. Also I love most of the changes to the rest of the code but it would be awesome if you could add back the loops in the functions we've definted for induvidual sites since the current code would only visit one site once before moving to the next, but we want it to visit a site and stay there for a while to emulate data better, as if the user is browsing through the site. For most of the sites this would be just adding a loop that runs a random number of times, but the reddit one we need to start the loop after we visit a specific subreddit.

**Comment by nikshepsvn** [comment]
Also, we need that part that randomly calls the sites, because as of now, you've just called the sites in order,so right now it would always be ie. Reddit --> Amazon --> Youtube --> Reddit --> Amazon ....

**Comment by nikshepsvn** [comment]
You've also taken out the random website function, Though I was going to re-write that anyway, keep it in the code so we can edit it later!

**Comment by nikshepsvn** [comment]
Also, the get_input function is necassary to know what sites we should iterate over! While making changes, just look over the old code to make sure we don't loose out on functionality!

**Comment by rsfxiii** [comment]
Thanks for the feedback, Nik! I was actually trying to assign each function a key and randint into them. It wasn't working on the first pass of approaches, so I moved on to the rest until I could come back to it.

The logic behind me removing the input was that since we're not logged in and the traffic is, by definition, unrelated to the user, then it actually doesn't need to be requested of them, right?

Couldn't we iterate over all site options and obfuscate their traffic further this way?

**Comment by nikshepsvn** [comment]
It was my pleasure :) 

That's alright -- just make sure you run the program and test the changes before making a pull request. It's easier to come across bugs that way! Regarding the input function, the ISP's cant see if we're logged in or not. I'm actually thinking of completely reversing the way the popular site function works -- My current plan is take an input of what sites they browse the most and actually iterate over them LESS instead of more, since they are browsing through those sites themselves, instead I was thinking of getting a list of the top 200 sites and just iterating over them -- so then it would be hard to differentiate between the popular sites they browse (for ex : tumblr, reddit maybe?) and all the popular sites in general (ex : 4chan, amazon, some news site) from the data

**Pull request closed without merging**
